var planets = ["mercury","venus","uranus","jupiter","earth"]
console.log(planets)
planets.pop("venus")
console.log(planets)
planets.push("saturn")
console.log(planets)
planets.shift()
console.log(planets)
planets.splice(2,1)
console.log(planets)